### ISSUE TITLE
With Quarkus 3.3.0

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-qute-server-pages#39]
```
2023-08-24 09:52:55,652 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-4) HTTP Request to / failed, error id: 725c1659-8bb1-4579-882a-5f2c5e765f56-1: java.lang.NoSuchMethodError: 'void io.quarkus.arc.ManagedContext.activate()'
    at io.quarkiverse.quteserverpages.runtime.QspHandler.handle(QspHandler.java:82)
    at io.quarkiverse.quteserverpages.runtime.QspHandler.handle(QspHandler.java:36)
    at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
    at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
    at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
    at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
    at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
    at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
    at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
    at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by gsmet** [comment]
The return value of the method changed. The extension needs to be recompiled for 3.3. 

Do it in a minor as we need to keep a version compatible with 3.2.

**Comment by mkouba** [comment]
Unfortunately, https://github.com/quarkusio/quarkus/pull/35246 (main, aka 3.4) will break the `QspHandler` again.

> Do it in a minor as we need to keep a version compatible with 3.2.

@gsmet What do you mean with "do it in a minor"? We can't recompile against 3.3 and keep the 3.2 as the target. I'm going to:

1. Create a 2.0.x branch (targets 3.2)
2. Main will target Quarkus 3.3
3.  Release 2.1.0 targeting 3.3

**Comment by mkouba** [comment]
For the record - this particular compatibility issue should be fixed in https://github.com/quarkusio/quarkus/pull/35615.

**Comment by gsmet** [comment]
>  Create a 2.0.x branch (targets 3.2)
>  Main will target Quarkus 3.3
>  Release 2.1.0 targeting 3.3

Exactly what I had in mind.

**Comment by mkouba** [comment]
https://github.com/quarkiverse/quarkus-qute-server-pages/releases/tag/2.1.0.Final
